### ISSUE TITLE
Keys for non-url friendly filenames are getting encoded multiple times.

### ISSUE THREAD

**Issue by jimjeffers** [dwilkie/carrierwave_direct#113]
Hi, I posted my problem on SO but I think it would be better served here. Original question can be seen here:

http://stackoverflow.com/questions/19645506/how-can-i-force-url-friendly-filenames-when-using-carrierwavedirect-in-ruby-on-r

I have users uploading files with non url friendly names. Mainly, filenames that include spaces. I have an admin area where moderators can approve a photo. In the admin tool the image_url works just fine. The image path is url escaped with %20 in place of the spaces. The trouble is when the moderator approves the photo I make a simple asynchronous JSON POST request which in simply does this:

```
 def approve
    photo = Photo.find(params[:id])
    status = photo.update_attribute :approved, true

    respond_to do |wants|
      ...
    end
  end
```

As a result of that call to update_attribute I see a SQL statement like this:

```
SQL: (1.7ms) UPDATE "photos" SET "approved" = 't', "image" = '02216914-1e9e-4b63-8ae6-80e24cb87f7a/5918%25201%2520photo.jpg', "updated_at" = '2013-10-29 05:31:31.779058' WHERE "photos"."id" = 302
```

Now the image path is broken as the database is storing a twice encoded string when the internal string shouldn't be encoded at all. At least, I don't think it should. I do not know why the image attribute is also being updated during this call. Any idea why this is and/or is there a better way to be managing non url-friendly filenames from user generated content?

- Jim

**Comment by p8** [comment]
This should be fixed on master with #155
