### ISSUE TITLE
direct_upload_form_for returns undefined method `model_name' for FileUploader:Class

### ISSUE THREAD

**Issue by sheharyarn** [dwilkie/carrierwave_direct#117]
I've been struggling with this for a couple of hours now. When using carrierwave_direct's `direct_upload_form_for` in my view, it returns me this error:
![enter image description here](http://i.stack.imgur.com/xuiLP.png) 

**FileUploader Carrierwave Class:**

```
class FileUploader < CarrierWave::Uploader::Base
  include CarrierWaveDirect::Uploader
end
```

**ManualFile Model:**

```
class ManualFile
  include Mongoid::Document
  mount_uploader :file, FileUploader

  field :name, :type => String
end
```

**UploadController:**

```
class UploadController < ApplicationController
    def manual_new
        @uploader = ManualFile.new.file
        @uploader.success_action_redirect = upload_edit_path
    end

    def manual_edit
        @myfile = ManualFile.new(key: params[:key])
    end
end
```

**My View:**

```
<%= direct_upload_form_for @uploader do |f| %>
  <%= f.file_field :file %>
  <%= f.submit %>
<% end %>
```

I can't understand what I'm doing wrong. I tried to follow this [railscast](http://railscasts.com/episodes/383-uploading-to-amazon-s3). I'm using Ruby 1.9.3, Rails 3.2.3, Mongoid 3 with carrierwave gems pointing to github master.

**Comment by ajsharp** [comment]
Any chance of adding mongoid support to resolve this issue?

**Comment by p8** [comment]
I'd gladly look at  a pull request for mongoid support.
