### ISSUE TITLE
Carrierwave Direct changes old uploads path

### ISSUE THREAD

**Issue by shlomizadok** [dwilkie/carrierwave_direct#118]
Hi,
Until recently we have used CarrierWave gem to upload our files.
We have now changed to carrierwave_direct and it works excellently (thanks!), besides one issue:

When we update model's attribute, without changing the file, when saving it adds the store_dir parameter anyhow, so if in my Book model - one book looked like:
{ name => "Hello Carrierwave Direct",  key => "books/hello.epub" } 
After editing (the name only) it would change to
{ name => "Hello edited name",  key => "books/books/hello.epub" } 

It adds automatically "books/" (yet it will not add the "books" if I have replaced the file via carrierwave_direct

Any clue?

**Comment by p8** [comment]
This should be fixed on master
