### ISSUE TITLE
Condition:  "starts-with", "$utf8"

### ISSUE THREAD

**Issue by Rodeoclash** [dwilkie/carrierwave_direct#137]
I had a little bit of trouble with this field when uploading to S3 via AJAX (using the angular-file-upload module). It seems that the upload could not satisfy the $utf8 criteria. To get around it I forked the repo and removed the condition.

However, things are a bit unclear exactly how to solve this. Does the entire AJAX post need to be in UTF-8? Is their a header that needs to be explicitly set? I have a working solution to the problem but removing the field is not ideal as I assume its their for a reason. If anyone can weigh in with a fix, that would be great and I would be happy to type it up and make a pull request to get it into the projects Readme.

**Comment by jhorsch** [comment]
Im getting this error when trying to upload. Is this relatable to the questions above?

ERROR

The request could not be satisfied.

This distribution is not configured to allow the HTTP request method that was used for this request. The distribution supports only cachable requests. 
Generated by cloudfront (CloudFront)
Request ID: DPQFbm6Sa47NSe9Cm8XMuU0YF-agOgsben5wwcUgC_EqfJcY_X0CiQ==
