### ISSUE TITLE
Two fields, one model.

### ISSUE THREAD

**Issue by faucct** [dwilkie/carrierwave_direct#148]
Stuff like this doesn't work, only figure files are uploaded correctly, because every field has to use the same attribute ":key" for returned key value.

class Question < ActiveRecord::Base
  mount_uploader :video_file, VideoFileUploader
  mount_uploader :audio_file, AudioFileUploader
  mount_uploader :figure_file, FigureFileUploader
end

**Comment by Ricardonacif** [comment]
I'm facing that. Isn't it supported?

**Comment by fabn** [comment]
#159 address this. Wait to see it that PR can be safely merged.
