### ISSUE TITLE
carrierwave_direct in model specs

### ISSUE THREAD

**Issue by sebastianzillessen** [dwilkie/carrierwave_direct#163]
Hi there,

I try to get my specs working. I have a model `Attachment` which has a file attribute `attachment`. Now I want to provide a mocked attachment through my factory (I use `FactoryGirl`). I use Ruby (2.1.3) on Rails (4.0.2). I Upload the files to amazon s3.

What I tried so far is:

```
# config/initializers/carrierwave.rb
if (Rails.env.test?)
  Fog.mock!
end
CarrierWave.configure do |config|
  config.fog_credentials = {
      provider: "AWS",
      aws_access_key_id: s3['access_key_id'],
      aws_secret_access_key: s3['secret_access_key'],
      region: s3['region']
  }
  config.fog_directory = s3['bucket']
  config.max_file_size = 500.megabytes
end


# factories/models/attachments.rb
include CarrierWaveDirect::Test::Helpers
FactoryGirl.define do
  factory :attachment do
    ...
    attachment { sample_key(AttachmentUploader.new, filename: "#{SecureRandom.hex}file.pdf") }
  end
end
```

This seems to work somehow, at least I get a valid attachment entry with some properties set:

```
 #<AttachmentUploader:0x007faaa595fae0 @model=#<Attachment id: 141, ... , >, @mounted_as=:attachment, @key="uploads/f97a1258-40b3-4850-8841-0bd17c1621b2/${filename}", @storage=#<CarrierWave::Storage::Fog:0x007faaa58fb6a8 @uploader=#<AttachmentUploader:0x007faaa595fae0 ...>>> 
```

But when I try to check if the attachment is present or not every location is nil:

```
a.attachment.path
 => nil 
a.attachment.file
 => nil 
```

Any ideas how I can fix this and how it is done correctly?

Thanks a lot!

**Comment by vemv** [comment]
Well, you are mocking Fog so it's reasonable that path and file are nil?

Personally I use real S3 in tests (with Capybara), using a dedicated bucket.

**Comment by p8** [comment]
Possibly related to https://github.com/dwilkie/carrierwave_direct/issues/111
