### ISSUE TITLE
direct_fog_url uses asset host url when it shouldn't

### ISSUE THREAD

**Issue by ajsharp** [dwilkie/carrierwave_direct#164]
I have the `asset_host` carrierwave config option set to a cloudfront url, and when I use the `direct_upload_form_for` it uses the cloudfront url as the action url. There doesn't appear to be a way to over-ride this, so maybe a reasonable solution would be to be able to pass an action_url option into `direct_upload_form_for`.

**Comment by p8** [comment]
Could you try master? This might fix it because it uses carrierwave for generating the url's.

**Comment by jhorsch** [comment]
you can allow POST requests from your cloudront distribution

**Comment by asoules** [comment]
I also hit this snag, found this article helpful is getting CloudFront configured correctly for POSTs: http://blog.celingest.com/en/2014/10/02/tutorial-using-cors-with-cloudfront-and-s3/
