### ISSUE TITLE
ArgumentError -  is not a recognized storage provider

### ISSUE THREAD

**Issue by tayyabshabab** [dwilkie/carrierwave_direct#169]
I have been working in sinatra. I followed all the instructions given but still this error is coming for me.

ArgumentError -  is not a recognized storage provider:
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/fog-core-1.29.0/lib/fog/storage.rb:27:in `new'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/storage/fog.rb:102:in `connection'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/storage/fog.rb:356:in `connection'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/storage/fog.rb:368:in `directory'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/storage/fog.rb:309:in `public_url'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/carrierwave_direct-0.0.14/lib/carrierwave_direct/uploader/direct_url.rb:6:in `direct_fog_url'
	/Users/tayyabshabab/code/hldesign/chris-juicebar/views/interviews/_form.slim:36:in `block in singleton class'
	/Users/tayyabshabab/code/hldesign/chris-juicebar/views/interviews/_form.slim:-1:in `instance_eval'
	/Users/tayyabshabab/code/hldesign/chris-juicebar/views/interviews/_form.slim:-1:in `singleton class'
	/Users/tayyabshabab/code/hldesign/chris-juicebar/views/interviews/_form.slim:-3:in `__tilt_70224959658980'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `evaluate'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:814:in `render'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:742:in `slim'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-partial-0.4.0/lib/sinatra/partial.rb:77:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-partial-0.4.0/lib/sinatra/partial.rb:77:in `partial'
	/Users/tayyabshabab/code/hldesign/chris-juicebar/views/interviews/create.slim:3:in `block in singleton class'
	/Users/tayyabshabab/code/hldesign/chris-juicebar/views/interviews/create.slim:-1:in `instance_eval'
	/Users/tayyabshabab/code/hldesign/chris-juicebar/views/interviews/create.slim:-1:in `singleton class'
	/Users/tayyabshabab/code/hldesign/chris-juicebar/views/interviews/create.slim:-3:in `__tilt_70224959658980'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `evaluate'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:814:in `render'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:742:in `slim'
	/Users/tayyabshabab/code/hldesign/chris-juicebar/controllers/interviews-controller.rb:22:in `block in <class:InterviewsController>'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:945:in `forward'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1019:in `route_missing'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:980:in `route!'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/nulllogger.rb:9:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:945:in `forward'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1019:in `route_missing'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:980:in `route!'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/nulllogger.rb:9:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:225:in `context'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:220:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/nulllogger.rb:9:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/methodoverride.rb:22:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/urlmap.rb:66:in `block in call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/urlmap.rb:50:in `each'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/urlmap.rb:50:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/tempfile_reaper.rb:15:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/lint.rb:49:in `_call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/lint.rb:37:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/showexceptions.rb:24:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/commonlogger.rb:33:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:217:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/chunked.rb:54:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/content_length.rb:15:in `call'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:86:in `block in pre_process'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `catch'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `pre_process'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:53:in `process'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:39:in `receive_data'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thin-1.6.3/lib/thin/backends/base.rb:73:in `start'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thin-1.6.3/lib/thin/server.rb:162:in `start'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/handler/thin.rb:19:in `run'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/server.rb:286:in `start'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/server.rb:147:in `start'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/bin/rackup:4:in `<top (required)>'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/bin/rackup:23:in `load'
	/Users/tayyabshabab/.rbenv/versions/2.1.5/bin/rackup:23:in `<main>'

I have removed storage :fog in ImageUploader class. But when in form I use @uploader.direct_fog_url then this error comes in.

Please help me solving it.

**Comment by nddeluca** [comment]
This appears to be an issue with your fog configuration. Can you please post any carrierwave and fog configuration you have set (with any credentials blanked out)? Thanks!

**Comment by tayyabshabab** [comment]
I am credentials like this

CarrierWave.configure do |config|
  config.fog_credentials = {
    :provider               => 'AWS',
    :aws_access_key_id      => 'xxxxxxxxx',
    :aws_secret_access_key  => 'xxxxxxxxxxxxxxxxxxxx'
  }
  config.fog_directory  = 'xxxxxxxx'
end

**Comment by nddeluca** [comment]
Thanks, I don't see any issue there.  Do you have the `fog`/`fog-aws` in your Gemfile and are you loading that configuration before using the uploader?  `YourUploader.fog_credentials` should contain the same fog_credentials that you have in you're carrierwave configuration

**Comment by tayyabshabab** [comment]
I have checked now and the configurations were loading after the uploader. I loaded them before uploader and it is working fine. Thanks a lot for your help.

**Comment by tayyabshabab** [comment]
I have one more problem coming up. After uploading the file to amazon, I get a key in response. But when I try submit the form with the key, I receive an error saying

ActiveRecord::UnknownAttributeError - unknown attribute 'key' for Interview

I am using ActiveRecord but CarrierWaveDirect is not giving key attribute in the model. What should I do to solve this problem?

**Comment by sono123** [comment]
Same issue (ActiveRecord::UnknownAttributeError - unknown attribute 'key'). Did anyone solve this?
