### ISSUE TITLE
Is it possible to direct upload to s3 and save a new record with metadata in one form?

### ISSUE THREAD

**Issue by jhorsch** [dwilkie/carrierwave_direct#174]
From what I've read it seems that you must have a form for the image upload and another form to submit other attributes to the model.  This makes it a two step process.

Is it possible to have just one form where the user uploads the image, enters in other meta data (ex title, desc, etc) , and then presses a save button.  This will then store the image on s3 and do all the processing in the background in addition to saving all the metadata to the DB.

If not, can you explain why this is not possible?

Thanks

**Comment by mdh** [comment]
When you post a form on the web, it is sent to the url that is specified in the action attribute of the form tag.

In your case, you want to sent data to s3 AND to your app/db. Those are to different urls, and thus need 2 forms. I suppose you could make 1 page with 2 forms (that look like 1) and use javascript/ajax to post to both urls in the background.

**Comment by jhorsch** [comment]
Thanks for the response. I had a feeling ajax would be the solution if wanting to show just one page.

I do have one other question.

In my Carrierwave uploader file, one of the versions uses MiniMagik to do a composite overlay.  I take the uploaded image and overlay it onto a background image.  I find the correct background image by calling http://www.example.com/#{model.background_image_id}.jpg in the carrierwave uploader. 

This worked just fine when I used the Carrierwave background gem, but I couldn't use that gem. In heroku production you can not write temp files to heroku server.  This is why I am now looking into carrierwave direct.

The background image chosen depends on a value from a drop down on the form.  Can I pass that value into the uploader form?  For example

<%= direct_upload_form_for @uploader do |f| %>
  <%= f.input :avatar %>
  <%= f.input :background_image %>
  <%= f.submit %>
<% end %>

OR  

Is that 'direct_upload_form_for' used only to upload the original temp file to s3?  Then once you create a new User  and attempt to save, a copy of the temp file is pulled from s3 to do then do all the processing?  In that case the background_image.id would be sent in the User form and would be available during processing? 

<%= form_for @user do |f| %>
  <%= f.hidden_field :key %>
  <%= f.input :email %>
  <%= f.input :background_image %>
  <%= f.submit %>
<% end %>

Thanks

**Comment by p8** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
