### ISSUE TITLE
Why the need to 'update the uploader object with the returned key in the controller action that corresponds to new_user_url:'

### ISSUE THREAD

**Issue by jhorsch** [dwilkie/carrierwave_direct#175]
The docs states:
After uploading to S3, You'll need to update the uploader object with the returned key in the controller action that corresponds to new_user_url:

@uploader.update_attribute :key, params[:key]

I'm not quite sure why this line is necessary given that the key value is stored in the new user form as a hidden field.  I also do not see that line of code mentioned in the new action on the Users controlelr (which is the controller action that corresponds to new_user_url)

class UsersController < ApplicationController
  def new
    @user = User.new(params)
    unless @user.filename_valid?
      flash[:error] = @user.errors.full_messages.to_sentence
      redirect_to new_avatar_path
    end
  end
end

While debugging the user form entry I see the value for key  "key"=>"development/photo/image//8913489f-bde3-4e06-bdd6-8b913c8cf0a0/${filename}"

Why does $(filename) exists instead of the actual file name?

Can someone please explain?

**Comment by nddeluca** [comment]
The `${filename}` variable is for interpolate with the real filename that the user uploaded.  All it does is tell amazon that it may replace that part of they key with the filename.  You can find the documentation here: http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-HTTPPOSTForms.html and here is amazons description of its use:

>The variable ${filename} is automatically replaced with the name of the file provided by the user and is recognized by all form fields. If the browser or client provides a full or partial path to the file, only the text following the last slash (/) or backslash (\) will be used (e.g., "C:\Program Files\directory1\file.txt" will be interpreted as "file.txt"). If no file or file name is provided, the variable is replaced with an empty string.

Since we don't know in advance the name of the file the user will upload, we let amazon take the key, insert the filename, and give us the full path (aka the key) back, so we know what the name of the file was.

**Comment by jhorsch** [comment]
Thanks for that.  I am still a little confused as to where to use this line of code.

@uploader.update_attribute :key, params[:key]

I didn't see it in the example application either.
https://github.com/dwilkie/carrierwave_direct_example/blob/master/app/controllers/users_controller.rb

Is the answer provided on this article a correct way to implement it?
http://stackoverflow.com/questions/17620853/no-update-attribute-method-on-carrier-wave-direct

When debugging my new action in the Photo (same as user from example)  controller, I see

>> params[:key]
=> "path//2642eb6a-928b-4025-b182-a6dee91f7328/med_res.jpg"
>> @photo = Photo.new(key: params[:key])
=> #<Photo id: nil, title: nil, created_at: nil, updated_at: nil, id_num: nil, year_taken: nil, is_active: true, show_bw_conversion: false, format_id: nil, rotating_keyword: "photo", category_id: nil, film_type: nil, slug: nil, qty_sold: 0, photographer_id: nil, daily_deal: nil, default_mat: nil, default_frame: nil, description: nil, qty_download: 0, image: nil>

However the filename_valid method keeps returning false. Is that a method from a Carrierwave Direct class? I'm confused as to whey it is not validating when the key shows up in the params hash

def new
    @photo = Photo.new(key: params[:key])
    #not recognizing filename
    unless @photo.filename_valid?
      flash[:error] = @photo.errors.full_messages.to_sentence
      redirect_to new_photo_path
    end
  end


Thanks

**Comment by p8** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
