### ISSUE TITLE
direct_fog_url being set to carrierwave default_image instead of image uploaded

### ISSUE THREAD

**Issue by jhorsch** [dwilkie/carrierwave_direct#176]
Hi,

I am trying to understand why the direct_fog_url returns the path to my default url instead of the path to my uploaded image 'med_res.jpg' with the following key

ImageUploader.rb
def default_url
   "https://s3-us-west-2.amazonaws.com/luminoto/worlds_first_camera.jpg"
  end

UploadsWorker.rb
def perform(photo_id, image_key)
    photo = Photo.find(photo_id)
    photo.key = image_key
    photo.remote_image_url = photo.image.direct_fog_url(:with_path => true)
    binding.pry
   photo.save!
  end

console
[6] pry(#<UploadsWorker>)> photo.key
=> "development/photo/image/8b6ad024-adaa-4f0e-af71-d4f12c9f288f/med_res.jpg"

[7] pry(#<UploadsWorker>)> photo.image.direct_fog_url(:with_path => true)
=> "https://d9vwx0ll7rhpx.cloudfront.net/uploads/tmp/1427316979-29456-6641/default_image.jpg"

**Comment by p8** [comment]
What happens if you save the photo after setting the key?

```ruby
def perform(photo_id, image_key)
  photo = Photo.find(photo_id)
  photo.key = image_key
  photo.save!
  photo.remote_image_url = photo.image.direct_fog_url(:with_path => true)
  binding.pry
  photo.save!
end
```

**Comment by jhorsch** [comment]
I keep getting the same issue.  Even if I directly name the correct path as in 'uploaded_photo_path' I still get this file attachment missing error in the sidekiq server log.

 def perform(photo_id, image_key)
    photo = Photo.find(photo_id)
    photo.key = image_key
    uploaded_photo_path = photo.image.direct_fog_url(:with_path => false).to_s + image_key.to_s
    photo.remote_image_url = uploaded_photo_path
    photo.save!
  end

ActiveRecord::RecordInvalid: Validation failed: Image attachment is missing

**Comment by jhorsch** [comment]
Everything works when I run the sidekiq process right away using 'new.perform', but when I use 'perform.async'

UploadsWorker.perform_async(new_photo.id, new_photo.key)

I get the following error in the sidekiq gui...

ActiveRecord::RecordInvalid: Validation failed: Image attachment is missing

This scenario works..but nothing is done in the background.

UploadsWorker.new.perform(new_photo.id, new_photo.key)

def perform(photo_id, image_key)
    photo = Photo.find(photo_id)
    uploaded_photo_path = photo.image.direct_fog_url(:with_path => false).to_s + image_key.to_s
    photo.remote_image_url = uploaded_photo_path
    photo.save
  end

**Comment by p8** [comment]
Glad you got it solved.
