### ISSUE TITLE
How can you validate image dimensions before uploading to s3?

### ISSUE THREAD

**Issue by jhorsch** [dwilkie/carrierwave_direct#177]
For my app, images need to be uploaded with a specific crop ratio (width / height ) so I need to verify the pixel dimensions before the image is uploaded to s3.  Is this possible when using carrierwave direct?

Also, I see that we can set max/min file size in the carrierwave initializer.  Can we do the same for width/height?

As for the file size...if the constraints are not met, the user is thrown a nasty error message in the browser like so ...
http://i.imgur.com/Y1zDm2j.png

Any way to redirect the user back to the upload page with a notice?

Thanks

**Comment by p8** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
