### ISSUE TITLE
I just want to test uploading to a local directory

### ISSUE THREAD

**Issue by HuckyDucky** [dwilkie/carrierwave_direct#179]

**Comment by fabn** [comment]
Could you elaborate your request?

If you want to upload locally you don't need this gem.

If you want to use local uploads only in tests you can do something like this

```ruby
# In your uploader class
storage(Rails.env.test? ? :file : :fog)
```


Closing for now, reopen if needed.

**Comment by hraynaud** [comment]
@fabn does this gem work with the fog-local gem?  This would be a great feature Then we could configure local uploads on dev and test and s3 in production.
Supper helpful If i need to test with internet access for example.

**Comment by p8** [comment]
@hraynaud I don't know if it works with fog-local. It might just work.
