### ISSUE TITLE
Won't redirect after successful upload?

### ISSUE THREAD

**Issue by Harrisonl** [dwilkie/carrierwave_direct#180]
When I upload a file it goes through to my s3 bucket and is all fine there but for some reason my app doesn't redirect? It just stays on the same page. I had a look at the logs and nothing changes, nor do I get back any key. 

Heres my form:

```haml
= direct_upload_form_for @uploader do |f|
  = f.file_field :text_file
  = f.submit
```

and my controller

```ruby
  def upload
    @uploader = Submission.new.text_file
    @uploader.success_action_redirect = new_submission_path
  end
```

**Comment by mikebuss** [comment]
@Harrisonl You may have solved this already, but just in case you haven't: I fixed this by switching the path to a URL. So:

```ruby
def upload
  @uploader = Submission.new.text_file
  @uploader.success_action_redirect = new_submission_url
end
```

**Comment by p8** [comment]
Thanks for the solution @mikebuss
