### ISSUE TITLE
Use fog-aws instead of fog

### ISSUE THREAD

**Issue by fabn** [dwilkie/carrierwave_direct#186]
This would have the following benefits:

* smaller memory footprint (only a part of fog would be required)
* simpler code?
* support [new signature scheme](https://github.com/fog/fog-aws/blob/master/lib/fog/aws/signaturev4.rb)

Related to #183

Explore compatibility with carrierwave 0.10.0. It should definitely work with CW master branch.

**Comment by p8** [comment]
Fixed with 9b033a1bfeffe8ca9c1af5be15e2783e4db1de2a
