### ISSUE TITLE
Forbid uploaders pointing to attributes called 'file'

### ISSUE THREAD

**Issue by vemv** [dwilkie/carrierwave_direct#190]
Sucky to find a random SystemStackError and have to figure out that this was the issue https://github.com/dwilkie/carrierwave_direct/issues/18

By any chance can CarrierWaveDirect::Uploader prevent this error in a clean way?

**Comment by fabn** [comment]
That issue is already fixed in master, see #188 

Try it and reopen this issue if you encounter any problem.

**Comment by vemv** [comment]
Perfect, thanks!
