### ISSUE TITLE
Possible expiration related bug?

### ISSUE THREAD

**Issue by vemv** [dwilkie/carrierwave_direct#191]
I was experiencing an issue which after 3 painful hours I was finally able to debug.

The problem was that while file uploads < 1MB would succeed, anything > 1MB would result in a `net::ERR_CONNECTION_RESET` in Chrome, and in silent failure in Firefox/Safari.

I thought it had to do with `content-length-range` or who-knows-what, but no: the `expiration` value was at fault.

Doing the following change did the trick for me (uploader.rb):

```diff
- expiration' => Time.now.utc + options[:expiration],
+ expiration' => 30.days.from_now.utc + options[:expiration],
```

Note that I did not set any expiration-related configuration in my carrierwave.rb.

So, as I see it, the expiration was being set to approximately `Time.now + 1.seconds` - that's the only way only small file uploads were the ones succeeding, doesn't it?

So, anyone could give a think to that line of code and determine if something is wrong?

I work in UTC+1 timezone, and use carrierwave_direct in conjuntion with jquery-file-upload (https://github.com/blueimp/jQuery-File-Upload/wiki/Upload-directly-to-S3 ).

Cheers - Victor

**Comment by vemv** [comment]
Tomorrow I'll give you the exact `Time.now.utc + options[:expiration]` values which cause the issue, for easing debugging (now I'm very tired!)

**Comment by vemv** [comment]
Cosing since I cannot reproduce this anymore :/

As a cautionary measure I'm setting this in my carrierwave.rb:

`config.upload_expiration = 30.days`

**Comment by ro-puente** [comment]
Where did you add the `expiration' => 30.days.from_now.utc + options[:expiration]`? 

I'm trying to upload a 4mb file and I get the exact same error: `net::ERR_CONNECTION_RESET`

**Comment by vemv** [comment]
@ro-puente file is: https://github.com/dwilkie/carrierwave_direct/blob/master/lib/carrierwave_direct/uploader.rb

Did you set `config.upload_expiration = 30.days` in your carrierwave.rb?

Also, make sure we are actually about the same exact issue. In my case, small-sized uploads always succeeded.
