### ISSUE TITLE
How to customize Content-Disposition?

### ISSUE THREAD

**Issue by vemv** [dwilkie/carrierwave_direct#195]
Similar gems let you do the following:

`@uploader.add_field('Content-Disposition', 'inline')`

I don't see an API to add custom fields to be taken into account by S3?

Cheers - Victor

**Comment by p8** [comment]
This should be fixed with #196

**Comment by vemv** [comment]
Thanks - will try it in production this week!

I'd be good to keep the issue open until we check it works. Then a snippet could be added to the documentation.

**Comment by vemv** [comment]
I think it'll work fine but I can't check it at the moment (https://github.com/dwilkie/carrierwave_direct/issues/206), will retry later.

In any case, a gem version bump is needed for this feature!

**Comment by vemv** [comment]
I could try it now. It doesn't work, request will fail with 403:

```xml
<Error>
   <Code>AccessDenied</Code>
   <Message>Invalid according to Policy: Policy Condition failed: ["eq", "$response-content-disposition", "inline"]</Message>
   <RequestId>yyyyy</RequestId>
   <HostId>xxxxxx</HostId>
</Error>
```

This is the relevant ruby code I wrote:

```ruby
@uploader.policy do |conditions|
  conditions << {"response-content-disposition" => "inline"}
end
```

Maybe S3 policies really don't have to do with setting content-disposition?

**Comment by p8** [comment]
Content-disposition should not be set when uploading. You can pass it to the download url:
```model.attachment.url(:query => { 'response-content-disposition' => 'attachment' } )```
