### ISSUE TITLE
Policy Condition failed: ["starts-with", "$utf8", ""]

### ISSUE THREAD

**Issue by Overload119** [dwilkie/carrierwave_direct#199]
```
<Error><Code>AccessDenied</Code><Message>Invalid according to Policy: Policy Condition failed: ["starts-with", "$utf8", ""]</Message><RequestId>A1AA13A9F53FC78F</RequestId><HostId>mjV4fhkvwUKnSk+fllWtqcr63DRRUAi91kInaMHdbQPr9Y87U5t0Y+OoFcSaWzijOab9ekeM9NI=</HostId></Error>
```

I'm using Dropzone.js and a react component that inlines all the required properties as props. However, I can't get it to upload because of this issue. Here is what is passed through:

```
------WebKitFormBoundaryqf7zhaXVP3LfObjb
Content-Disposition: form-data; name="utf-8"


------WebKitFormBoundaryqf7zhaXVP3LfObjb
Content-Disposition: form-data; name="key"

uploads/b597673b-a6c8-4116-a6b6-89fe3e9ef2de/${filename}
------WebKitFormBoundaryqf7zhaXVP3LfObjb
Content-Disposition: form-data; name="AWSAccessKeyId"

[redacted]
------WebKitFormBoundaryqf7zhaXVP3LfObjb
Content-Disposition: form-data; name="acl"

public-read
------WebKitFormBoundaryqf7zhaXVP3LfObjb
Content-Disposition: form-data; name="success_action_status"

201
------WebKitFormBoundaryqf7zhaXVP3LfObjb
Content-Disposition: form-data; name="policy"

[redacted]
------WebKitFormBoundaryqf7zhaXVP3LfObjb
Content-Disposition: form-data; name="signature"

5cSmzzAg5m7YLPrj4dtfwSRyPrs=
------WebKitFormBoundaryqf7zhaXVP3LfObjb
Content-Disposition: form-data; name="file"; filename="Screen Shot 2016-03-30 at 4.17.13 PM.png"
Content-Type: image/png


------WebKitFormBoundaryqf7zhaXVP3LfObjb--
```

**Comment by Overload119** [comment]
I fixed it - I was using `utf-8` instead of `utf8` in the form data.

```
    this.dropzone.on('sending', (_, xhr, formData) => {
      ...
      formData.append('utf8', '');
      ...
    });
```

**Comment by kylefox** [comment]
Thanks for posting this. I've been struggling to get this working for hours now!

I couldn't seem to find anything in the carrierwave_direct or Amazon S3 docs that explain what this `utf8` parameter is doing...

**Comment by nddeluca** [comment]
The `utf8` parameter isn't used by S3, and our documentation does a poor job describing it's purpose.

It's a by product of using the rails form builder to build the POST form to S3.  Rails 4.0 and below always includes a hidden field to force IE to respect UTF-8 encoding on form submission.

With that attribute present, we have to include a `[ "starts-with", "$utf8", "" ]` condition in the policy to tell S3 to allow that field in the form (even though S3 ignores it).

Rails 4.1 and above now allows that hidden field to be removed through an option when building the form, but completely removing it from the policy would be backwards incompatible.

**Comment by kylefox** [comment]
Aha, that makes sense. Thanks for clarifying, @nddeluca.

I saw the option to disable this functionality by passing `uploader.policy(enforce_utf8: false)`, and that `@object.policy(enforce_utf8: true)` is hard-coded into the form builder.

Think there's any value in allowing this parameter to be configured when used inside CarrierwaveDirect's form builder? In my case I was using the builder to generate all the required hidden fields, but am submitting the file to S3 via AJAX. It'd be cool if I could use the builder and omit the `$utf` param so I don't need to use `formData.append('utf8', '');` as a workaround.

If there's interest, I could take a stab at something like this. I think it would be cool if CarrierwaveDirect offered more functionality for AJAX use cases 👍

**Comment by maestromac** [comment]
This issue is resolved. Please give it a try! one side note is that the frontend code is a bit buggy and the redirect may not be working right now but I'm working on it.
