### ISSUE TITLE
Instantiating with key fails when multiple uploaders attached to AR model

### ISSUE THREAD

**Issue by HuckyDucky** [dwilkie/carrierwave_direct#200]
I have a model called `Upload`. It has a `text_file_name` and a `return_file_name`.

I process the `text_file_name` after the file is uploaded. I kick errors out to the `return_file_name`. In my background jobs, this works flawlessly. I even mount the same uploader to both fields. No reason not to.

But now my upload view tests are failing. It seems that this instantiantion:

```
@upload = current_subscription.uploads.new(key: params[:key])
```

no longer works. Makes sense, because it doesn't know which column to assign it to I guess? But this doesn't work either:

```
@upload = current_subscription.uploads.new(text_file_name_key: params[:key])
```

I'm really hoping I'm overlooking something, because this is a nice solution. I don't want to have to create another model just for my use case.

**Comment by p8** [comment]
On master we now support multiple keys. This should probably work:
    @upload = current_subscription.uploads.new(text_file_name_key: params[:key])
