### ISSUE TITLE
Needs a version bump

### ISSUE THREAD

**Issue by snex** [dwilkie/carrierwave_direct#210]
The binary on rubygems does not contain the latest version, which makes following the README lead to NoMethodErrors, for example:

> uploader = AvatarUploader.new
=> #<AvatarUploader ...>
> uploader.credential
NoMethodError: undefined method `credential' for #<AvatarUploader ...>

Bumping the version should force rubygems to fetch the latest code.

**Comment by p8** [comment]
Done!
