### ISSUE TITLE
Use CarrierWave 1.0

### ISSUE THREAD

**Issue by otagi** [dwilkie/carrierwave_direct#211]
CarrierWave has officially passed the 1.0 mark, with [some breaking changes](https://github.com/carrierwaveuploader/carrierwave/blob/master/CHANGELOG.md#100beta---2016-09-08) compared to 0.11.

I'm working on a [CarrierWaveDirect update](https://github.com/otagi/carrierwave_direct/commit/56e23b063cd153df13bb91b33af4531a667a9f2e), but I'm using Google Storage instead of AWS, so I'm not sure if the following error is specific to Google or not.

I get this `403` from Google Storage: 

```xml
<Error>
  <Code>
    SignatureDoesNotMatch
  </Code>
  <Message>
    The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.
  </Message>
  <StringToSign>
    <!-- Long encoded string -->
  </StringToSign>
</Error>
```

I'm stuck in the debug process at the moment, so if anyone else is working on a compatibility update, help would be much appreciated.

**Comment by kreintjes** [comment]
I have created a pull request adding Carrierwave 1.x support: https://github.com/dwilkie/carrierwave_direct/pull/213. This works fine for me in combination with AWS. 

@otagi maybe your error has something to do with "Upgraded signing algorithm to use AWS V4 POST authentication" introduced in [0.0.16](https://github.com/dwilkie/carrierwave_direct/blob/master/Changelog.md#0016-pending). Does the master branch (without your changes) work with Google storage?
