### ISSUE TITLE
use fog-aws dependency instead of fog in gem spec

### ISSUE THREAD

**Issue by barriault** [dwilkie/carrierwave_direct#212]
I believe this has already been fixed in the master branch, but it would be nice if you could add it to a stable release

**Comment by johnnyshields** [comment]
Better yet, do not require fog at all and just raise an error if some fog variant (was, google, etc) is not present at runtime.

**Comment by p8** [comment]
I'll try to release a new version in january

**Comment by p8** [comment]
I've released new versions.
