### ISSUE TITLE
One Form Action

### ISSUE THREAD

**Issue by MuneebSarfraz94** [dwilkie/carrierwave_direct#215]
i want to place my avatar upload file field in the same form which has user's email and other fields and do the same with one controller action is there any ways to do this? for example form should look like this?

<%= form_for(@user, @uploader) do |f| %>

  <%= f.hidden_field :key %>
  <%= f.text_field :email:  %>
  <%= f.file_field :avatar:  %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

**Comment by p8** [comment]
This does not work because the form can only be submitted to your server of S3, not both.

**Comment by mdh** [comment]
your server OR s3, not both
