### ISSUE TITLE
Need to create an upload programmatically

### ISSUE THREAD

**Issue by myfitment** [dwilkie/carrierwave_direct#228]
I have a need to occasionally programmatically create uploads to my Upload model. The upload er I have attached uses carrierwave_direct.

Unfortunately I get a "text_file_name is not valid" error when attempting this. I think it has to do with my not using :key.

However, I am not at all clear about how to set the key myself. You have helper methods for Capybara, and unit testing, but those don't work from application code.

I would really think that this is not an edge case.

Please help.

**Comment by p8** [comment]
Could you give a sample test case of what you would like to see?

**Comment by myfitment** [comment]
class FilePoller
      include Sidekiq::Worker

      def perform(files)
        files.each do |filename|
            # Create an Upload object off of the local filesystem
            upload = Upload.new(text_file_name: Rails.root.join(filename))
            upload.save!
            # LoaderWorker operates off of an upload object
            LoaderWorker.perform_async(upload.id)
          end
       end

    end

That's basically it. There's a parent worker that polls customer SFTP directories and picks up the files to hand off to this worker.

**Comment by myfitment** [comment]
I think I figured it out. I added:

        upload.text_file_name = File.open(Rails.root.join(basename))
        upload.text_file_key = upload.text_file_name.key

and it worked.
