### ISSUE TITLE
How do you validate presence?

### ISSUE THREAD

**Issue by dagumak** [dwilkie/carrierwave_direct#78]
After uploading to Amazon, when the key comes back, then I'm supposed to save the key. The key magically populates the avatar field in Users. So, if I validate avatar with presence, it will return back false because it hasn't been populated yet during the validation of the active record cycle, but the whole idea of trying to validate presence is so that the form doesn't send a request to Amazon. What's the proper way to validate presence then?

**Comment by p8** [comment]
Closed because of inactivity and questions belong on Stackoverflow.
