### ISSUE TITLE
What is the proper way to update an existing file?

### ISSUE THREAD

**Issue by davidwilliam** [dwilkie/carrierwave_direct#82]
I am able to upload a new file for an object but I can't upload another file for the same object.

Scenario:

I have the user details page (show.html.erb). Inside the show action of UsersController I have the following:

``` ruby
def show
  @uploader = current_user.avatar
  @uploader.success_action_redirect = link_avatar_url
end
```

And I have in the same controller, the action "link_avatar", as follows:

``` ruby
def link_avatar
    current_user.update_attribute :key, params[:key]
    redirect_to user_path
end
```

The code above works the very first time or whenever current_user.avatar = nil
But if I have already an avatar for the current_user, I got this:

``` xml
<Error>
  <Code>AccessDenied</Code>
  <Message>
    Invalid according to Policy: Policy Condition failed: ["starts-with", "$key", "uploads"]
  </Message>
  <RequestId>xxxxxxxxxxx</RequestId>
  <HostId>xxxxxxxxxxx</HostId>
</Error>
```

My CarrierWave configuration:

``` ruby
CarrierWave.configure do |config|
    config.fog_credentials = {
      :provider               => 'AWS',
      :aws_access_key_id      => 'xxxxxxxxx'
      :aws_secret_access_key  => 'xxxxxxxxx'
    }
    config.fog_directory  = "xxxxxxx"
end
```

My Gemfile:

``` ruby
gem 'carrierwave'
gem 'carrierwave_direct'
gem 'fog'
```

The form helper inside show.html.erb:

``` erb
<%= direct_upload_form_for @uploader do |f| %>
  <%= f.file_field :avatar %>
  <%= f.submit %>
<% end %>
```

What I am doing wrong?

Thanks in advance.

**Comment by p8** [comment]
This should be fixed on master
