### ISSUE TITLE
Keep default Carrierwave paths?

### ISSUE THREAD

**Issue by octimizer** [dwilkie/carrierwave_direct#98]
Hi, 

is there a way to use CarrierWaveDirect but keep the default store_dir filenames and paths from CarrierWave? 

Or how would you go about switching an existing Carrierwave project to CarrierWaveDirect without breaking paths and filenames and without having to regenerate versions ? (video attachments can be a pain to regenerate.)

**Comment by hankish** [comment]
Btw... The technique linked to above still felt a little hacky to me.  This is another technique to consider: http://stackoverflow.com/questions/14791655/carrierwave-direct-gem-keep-current-directory-structure-on-s3
